---
title: "PracticaFDA"
author: "Isabela Ignacio"
date: "27/11/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r librerias, include=TRUE}
library(readr)
library(ggplot2)
library(GGally)
library(dplyr)
library(tidyr)
library(missForest)

```

## Cargar los datos

```{r cargas datos, include=TRUE}
hospital_charges <- read_csv("notebooks/hospital-charges.csv")
head(hospital_charges)
summary(hospital_charges)

```
## Borrar los espacios de los headers

```{r cambiar columnas 1, include=TRUE}
names(hospital_charges) <- c('drg_def', 'prov_id', 'prov_name', 'prov_address', 'prov_city', 'prov_state', 
                   'prov_zip', 'referral_reg', 'total_discharges', 'mean_covered_charges',
                   'mean_total_payments', 'mean_medicare_payments')
head(hospital_charges)

```

## Eliminar dolar de las ultimas 3 columnas y cambiar los nombres de las columnas 

```{r cambiar dolares, include=TRUE}

hospital_charges$mean_covered_charges = as.numeric(gsub("\\$","",hospital_charges$mean_covered_charges))

hospital_charges$mean_total_payments = as.numeric(gsub("\\$","",hospital_charges$mean_total_payments))

hospital_charges$mean_medicare_payments = as.numeric(gsub("\\$","",hospital_charges$mean_medicare_payments))   

head(hospital_charges)

```
## Datos faltantes

```{r datos faltantes menos en las columnas 1,3,5,7,8,9,11,12 include=TRUE}

set.seed(1)
hospital_charges <-bind_cols(hospital_charges[c(1,3,5,7,8,9,11,12)],missForest::prodNA(hospital_charges[c(-1,-3,-5,-7,-8,-9,-11,-12)],noNA=0.1))

hospital_charges

```

```{r 80 training y 20 test include=TRUE}
set.seed(101)
sample <- sample.int(n=nrow(hospital_charges), size=floor(.80*nrow(hospital_charges)), replace = F)
train <- hospital_charges[sample,]
test <- hospital_charges[-sample,]

train
test

```
